extraction:
  cpp:
    after_prepare: 
      - python report.py 17
  cobol:
    after_prepare: 
      - python report.py 17
  csharp:
    after_prepare: 
      - python report.py 17
  java:
    after_prepare: 
      - python report.py 17
  javascript:
    after_prepare: 
      - python report.py 17
  python:
    after_prepare: 
      - python report.py 17
